import Head from 'next/head';
import App from 'next/app';
import '../styles/globals.css';
import theme from '../config/theme';
import { Footer, Navbar } from '../containers';
import { ThemeProvider } from '@emotion/react';
import { Provider } from 'react-redux';
import store from '../config/store';

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <ThemeProvider theme={theme}>
        <Navbar />
        <Head>
          <title>Simple Store</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
        <Footer />
      </ThemeProvider>
    </Provider>
  );
}

MyApp.getInitialProps = async appContext => {
  appContext.ctx.reduxStore = store;

  const pageProps = await App.getInitialProps(appContext);

  return { ...pageProps };
};

export default MyApp;
